import Aside from "./aside";
import Head from "next/head";

export default function Layout({ children, title }) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/icono.png" />
            </Head>

            <div className="flex h-screen overflow-y-auto bg-fondo">
                {/* mover el main al lado del aside */}
                <div className="basis-[20%] xl:basis-[20%] lg:basis-[15%] 2xl:basis-[15%]">
                    <Aside />
                </div>
                <main className="basis-[80%] px-6 py-4 xl:basis[80%] lg:basis[85%] 2xl:basis[85%]">
                    {children}
                </main>
            </div>
        </>
    );
}