import Aside from "./aside";
import Head from "next/head";
import Boton from "./boton";

export default function Layout({ children, title }) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/icono.png" />
            </Head>

            <div className="flex h-screen overflow-y-auto bg-fondo">
                {/* mover el main al lado del aside */}
                <div className="basis-[20%] xl:basis-[20%] lg:basis-[15%] 2xl:basis-[15%]">
                    <Aside />
                </div>
                <main className="basis-[80%] px-6 py-4 xl:basis[80%] lg:basis[85%] 2xl:basis[85%]">
                    {children}
                    <div className="flex flex-col justify-center items-center">
                          <Boton tipo = 'Ingresar' ancho='150px' alto='50px' letra='15px'/>
                          <Boton tipo = 'Filtrar' ancho='150px' alto='50px' letra='15px'/>
                          <Boton tipo = 'Confirmar' ancho='150px' alto='50px' letra='15px'/>
                          <Boton tipo = 'Cancelar' ancho='150px' alto='50px' letra='15px'/>
                    </div>
                </main>
            </div>
        </>
    );
}