import Head from "next/head";
import Link from 'next/link'
import Image from "next/image"
import Input from "components/input";
import Boton from "components/boton";
import { fontSize } from "@mui/system";


export default function Login() {
    var styles = {
        width: '1000px',
        height: '500px',
        backgroundColor: 'white',
        margin: '10px',
        padding: '10px',
        borderRadius: '10px',
        textAlign: 'center',
        justifyContent: 'center',
    }

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/icono.png" />
            </Head>

            <div className="flex h-screen overflow-y-auto bg-fondo items-center justify-center">
                <div style={styles} className='container overflow-hidden p-4 border-spacing-1 m-1'>
                    <div className="float-left text-center items-center w-1/2 justify-center h-full my-20">
                        <p className="py-6 font-bold" style={{ fontSize: '20px'}}>Inscripcion WEB</p>
                        <Input tipo='registro' />
                        <Input tipo='password' />
                        <br></br>
                        <Boton tipo='Ingresar' ancho='150px' alto='50px' letra='14px' className='my-10' />
                        <p className="py-0 font-medium" style={{ fontSize: '10px', color: '#0170F2' }}>¿Olvidaste tu contraseña?</p>
                    </div>
                    <div style={{ height: '70%', left: '50%', position: 'absolute', borderLeft: '1px solid #808080', color: 'gray' }}></div>
                    <div className="float-right p-8">
                        <Image src="https://scontent.fcbb2-1.fna.fbcdn.net/v/t39.30808-6/254492065_4876233149083206_1107629317053811200_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=szD_syyq-F4AX8w2ey-&_nc_ht=scontent.fcbb2-1.fna&oh=00_AfCX1326Z0y-Tc8pYQPoLTvgVyFR9SRR6WDLU45JovYg3g&oe=63FE0CBD" width={400} height={150} alt="" />
                    </div>

                </div>

            </div>
        </>
    )
}